name: 'Sofy-Azure-Webapp-Integration'
description: 'Greet someone and record the time'
inputs:
  website_url:  # id of input
    description: 'Website Endpoint to Run SOFY for WEB'
    required: true
    default: ''
  subscription_id:  # id of input
    description: 'Subscription ID'
    required: true
    default: ''
outputs:
  time: # id of output
    description: 'The time we queued the test'
runs:
  using: 'node12'
  main: 'index.js'